app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user_registration:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }
    
user_login:
    path: /security/login
    defaults: { _controller: AppBundle:Security:login }
user_login_check:
    path: /security/login_check
lougout:
    path: /security/logout
