# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    app.mailer.transport: sendmail

services:
    app.mailer:
        class:  AppBundle\Mailer
        arguments: ['%app.mailer.transport%']
    
    app.newsletter_manager:
        class: AppBundle\Newsletter\NewsletterManager
        arguments: ['@app.mailer']
        
    app.webservice_user_provider:
        class: AppBundle\Security\User\WebserviceUserProvider
