# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    app.mailer.transport: sendmail

services:
    app.mailer:
        class:  AppBundle\Mailer
        arguments: ['%app.mailer.transport%']
    
    app.newsletter_manager:
        class: AppBundle\Newsletter\NewsletterManager
        arguments: ['@app.mailer']
        
    app.webservice_user_provider:
        class: AppBundle\Security\User\WebserviceUserProvider
        
    bookingDatabase:
        class: %db.class%
        calls: 
           - [setDBMS, [%database.bookingDatabase.dbms%]]
           - [setHost, [%database.bookingDatabase.host%]]
           - [setUser, [%database.bookingDatabase.user%]]
           - [setDatabaseName, [%database.bookingDatabase.name%]]
           - [setPassword, [%database.bookingDatabase.password%]]
           - [setPort, [%database.bookingDatabase.port%]]

    bookingTable:
         class: AppBundle\Model\DbTable\Booking
         arguments: ["@service_container"]
