index:
    path:    /
    defaults: { _controller: AppBundle:Default:index }
    
user_registration:
    path:     /register
    defaults: { _controller: AppBundle:Registration:index }
    
user_login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }
    
user_login_check:
    path:     /loginCheck
    defaults: { _controller: AppBundle:Security:loginCheck }
    
user_lougout:
    path:     /logout
    defaults: { _controller: AppBundle:Security:logout }
    
user_password_resend:
    path:     /password-resend
    defaults: { _controller: AppBundle:Security:passwordResend }
    
article_new:
    path:     /article/new
    defaults: { _controller: AppBundle:Article:new }
    
article_show:
    path:     /article/new
    defaults: { _controller: AppBundle:Article:show }
    
profile:
    path:     /profile
    defaults: { _controller: AppBundle:Profile:index }
    
sidebar:
    path:     /sidebar
    defaults: { _controller: AppBundle:SideBar:index }
